/*
 * DAC_Config.h
 *
 *  Created on: Nov 5, 2023
 *      Author: Mostafa Sayed
 */

#ifndef DAC_CONFIG_H_
#define DAC_CONFIG_H_

/*	DAC DMA :	DAC_EN		DAC_DIS*/
#define DAC_DMA_CH1			DAC_DIS
#define DAC_DMA_CH2			DAC_DIS

/*	DAC_MSK_AMP_CH1 or DAC_MSK_AMP_CH2 :
 *  DAC_LFSR0_AMP1		 DAC_LFSR1_AMP3		 DAC_LFSR2_AMP7		 DAC_LFSR3_AMP15
 *	DAC_LFSR4_AMP31		 DAC_LFSR5_AMP63	 DAC_LFSR6_AMP127	 DAC_LFSR7_AMP255
 *	DAC_LFSR8_AMP511	 DAC_LFSR9_AMP1023	 DAC_LFSR10_AMP2047	 DAC_LFSR11_AMP4095
 *
 */
#define DAC_MSK_AMP_CH1	DAC_LFSR11_AMP4095
#define DAC_MSK_AMP_CH2	DAC_LFSR0_AMP1

/*	DAC Waveform  :	DAC_WAVE_DIS	DAC_WAVE_NO		DAC_WAVE_TRI */
#define DAC_WAVE_CH1		DAC_WAVE_DIS
#define DAC_WAVE_CH2		DAC_WAVE_DIS

/*	DAC Triggering event :
 * 	DAC_TRIG_TIM6	DAC_TRIG_TIM3	DAC_TRIG_TIM7	DAC_TRIG_TIM5
 * 	DAC_TRIG_TIM2	DAC_TRIG_TIM4	DAC_TRIG_EXT	DAC_SWTRIG
 */
#define DAC_TRIG_EVE_CH1	DAC_SWTRIG
#define DAC_TRIG_EVE_CH2	DAC_SWTRIG

/*	DAC TRIG :	DAC_EN		DAC_DIS*/
#define DAC_TRIG_SET_CH1	DAC_DIS
#define DAC_TRIG_SET_CH2	DAC_EN

/*	DAC BUFF :	DAC_EN		DAC_DIS*/
#define DAC_BUFF_SET_CH1	DAC_EN
#define DAC_BUFF_SET_CH2	DAC_EN

/*	DAC SWTRIG :	DAC_EN		DAC_DIS*/
#define DAC_SWTRIG_CH1		DAC_EN
#define DAC_SWTRIG_CH2		DAC_EN

/* DAC Register Resolution :	DAC_REG_RES_8BIT	DAC_REG_RES_12BIT		*/
#define DAC_REG_RES_CH1		DAC_REG_RES_12BIT
#define DAC_REG_RES_CH2		DAC_REG_RES_8BIT

/*	DAC Data Alignment : DAC_RIGHT_ALIG 	DAC_LEFT_ALIG */
#define DAC_DATA_ALIG_CH1	DAC_RIGHT_ALIG
#define DAC_DATA_ALIG_CH2	DAC_LEFT_ALIG

#endif /* DAC_CONFIG_H_ */
